import sys
import time

num1 = int(sys.argv[1])
num2 = int(sys.argv[2])

print()
time.sleep(1)
print( "Calculating ...")
time.sleep(1)
print()
print("Do Addition: ")
print(int(num1 + num2))
time.sleep(1)
print()
print("Do Subtraction: ")
print(int(num1 / num2))
time.sleep(1)
print()
print("Do Multiplication: ")
print(int(num1 * num2))
time.sleep(1)
print()
print("Do Division: ")
print(int(num1 % num2))
time.sleep(1)
print()
print("Finally Calculated ...")
print()