import time
time.sleep(1)
print()
num1 = int(input("Give me a Number: "))
print()
num2 = int(input("Give me the second Number: "))
print()
time.sleep(1)
print("Calculating ...")
time.sleep(1)
print()
print("The Addition is: ")
print(num1 + num2)
time.sleep(1)
print("The Subtraction is: ")
print(num1 - num2)
time.sleep(1)
print()
time.sleep(1)
print("Finally Calculated!")
print()